'use client'

import { type WorkflowCase, type AuditEvent } from '@/lib/workflow-engine'

function Field({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{String(value)}</strong></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="report-section"><h4>{title}</h4>{children}</section> }
function eventTimestamp(event?: Partial<AuditEvent> & { createdAt?: string; created_at?: string; created_at_timestamp?: string }) { return event?.timestamp || event?.createdAt || event?.created_at || event?.created_at_timestamp }
function formatTimestamp(value?: string) { if (!value) return 'Not recorded'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Not recorded' : date.toLocaleString('en-IN') }

export function DynamicReportPreview({ role = 'Inspector', caseId, generated, approved, onGenerate, serverCase, serverEvents = [] }: { role?: 'Inspector' | 'Lab Verifier' | 'Officer' | 'Admin'; caseId: string; generated: boolean; approved: boolean; onGenerate: () => void | Promise<void>; serverCase?: Partial<WorkflowCase>; serverEvents?: AuditEvent[] }) {
  const data = { item: serverCase as WorkflowCase | undefined, events: serverEvents }
  const item: WorkflowCase = data.item || { id: caseId, instrument: 'NAWI instrument', location: 'Not recorded', inspector: 'Not recorded', ownerRole: 'Inspector', status: 'DRAFT', evidenceComplete: false, evidenceStatus: 'INCOMPLETE', trustgateReady: 0, trustgateResult: 'Checks pending', reportUnlocked: false, reportGenerated: false, remarks: 'No remarks recorded.', updatedAt: new Date().toISOString() }
  const reportId = generated ? (item.reportId || 'Not generated') : 'Not generated'
  const status = generated ? 'REPORT_GENERATED' : item.status
  const returned = ['SENT_BACK_TO_INSPECTOR', 'RETEST_REQUESTED', 'POTENTIAL_NON_COMPLIANCE'].includes(item.status)
  const officerCanGenerate = role === 'Officer' && item.status === 'APPROVED' && !generated
  const title = generated ? 'NAWI Inspection Report' : officerCanGenerate ? 'Ready for Final Report' : 'Draft Report Preview'
  const date = formatTimestamp(item.updatedAt)
  const inspectionDate = item.inspectionDate || formatTimestamp(item.updatedAt)
  const field = (value: string | undefined, fallback: string) => value || fallback
  const labStatus = data.events.some(event => event.actorRole === 'Lab Verifier' && event.action.toLowerCase().includes('forward')) ? 'Forwarded to Officer' : (data.events.some(event => event.actorRole === 'Lab Verifier') ? 'Reviewed' : 'Pending')
  const officerEvent = data.events.find(event => event.actorRole === 'Officer' && (event.toStatus === 'APPROVED' || event.action.toLowerCase().includes('review')))
  const labEvent = data.events.find(event => event.actorRole === 'Lab Verifier')
  const officerName = officerEvent?.actorName || 'Officer review pending'
  const labVerifierName = labEvent?.actorName || 'Lab verifier pending'
  const evidenceRefs = item.evidenceComplete ? `EV-${item.id.replaceAll('-', '')}-01, EV-${item.id.replaceAll('-', '')}-02` : 'Pending capture'
  const grid = (values: [string, string | number][]) => <div className="report-grid">{values.map(([label, value]) => <Field key={label} label={label} value={value} />)}</div>
  return <section className="report-layout">
    <div className="report-toolbar"><div><p className="eyebrow">R 76-2 STYLE · {generated ? 'OFFICIAL REPORT' : 'DRAFT PREVIEW'}</p><h2>{title}</h2><p className="section-note">{returned ? 'Report cannot be generated because the case was returned for further action.' : role === 'Lab Verifier' && ['SUBMITTED_TO_LAB', 'LAB_REVIEW_IN_PROGRESS'].includes(item.status) ? 'Technical review is pending. Final report requires officer approval.' : generated ? 'Final report generated from the centralized workflow case.' : 'Final report can be generated only after officer approval.'}</p></div><div className="report-actions"><a className="secondary-button" href={`/cases/${caseId}`}>Back to Case Detail</a><a className="secondary-button" href={`/audit?caseId=${caseId}`}>Audit Trail</a><button className="secondary-button" disabled title="PDF export is not enabled in this preview">PDF Export {generated ? '(not available in prototype)' : '(available after final report generation)'}</button>{role === 'Officer' && officerCanGenerate ? <button className="primary-button" onClick={onGenerate}>Generate Report</button> : role === 'Officer' && generated ? <button className="primary-button" disabled>Report Generated</button> : null}</div></div>
    <div className="report-status-strip"><span>{status.replaceAll('_', ' ')}</span><span>Case {item.id} · Report ID {reportId}</span><span>Generated: {generated ? date : 'Pending'}</span></div>
    <article className="report-paper"><div className="report-header-block"><div><p className="eyebrow">LEGAL METROLOGY · DEPARTMENT OF CONSUMER AFFAIRS</p><h3>{title}</h3><p>Case-specific verification record</p></div><strong>{generated ? 'Generated' : officerCanGenerate ? 'Ready to Generate' : returned ? 'Returned for action' : 'Draft — not legally final'}</strong></div>
      <Section title="A · Report identity">{grid([['Case ID', item.id], ['Report ID', reportId], ['Current status', status], ['Generated timestamp', generated ? date : 'Pending'], ['Officer approval', approved ? 'Approved' : 'Pending'], ['Owner role', item.ownerRole]])}</Section>
      <Section title="B · Instrument identity">{grid([['Instrument type', field(item.instrument, 'NAWI instrument')], ['Manufacturer', field(item.manufacturer, 'Not recorded')], ['Model', field(item.model, 'Not recorded')], ['Serial number', field(item.serialNumber, 'Not recorded')], ['Accuracy class', field(item.accuracyClass, 'Not recorded')], ['Maximum capacity', field(item.maximumCapacity, 'Not recorded')], ['Minimum capacity', field(item.minimumCapacity, 'Not recorded')], ['Verification scale interval', field(item.verificationScaleInterval, 'Not recorded')], ['Location', field(item.location, 'Not recorded')]])}</Section>
      <Section title="C · Test setup">{grid([['Inspection date', inspectionDate], ['Inspector', field(item.inspector, 'Not recorded')], ['Test location', field(item.testLocation || item.location, 'Not recorded')], ['Environmental notes', field(item.environmentalNotes, 'Not recorded')], ['Test mass reference', field(item.testMassReference, 'Not recorded')], ['Setup status', item.status.includes('TEST') || item.evidenceComplete ? 'Completed' : 'Pending']])}</Section>
      <Section title="D · OIML applicability">{grid([['Rule/version used', field(item.oimlRule, 'Not recorded')], ['Selected checks', field(item.selectedChecks, 'Not recorded')], ['Applicability status', item.evidenceComplete ? 'Applicable checks selected' : 'Pending selection']])}</Section>
      <Section title="E · Evidence summary">{grid([['Evidence status', item.evidenceStatus], ['Evidence completeness', item.evidenceComplete ? 'Complete' : 'Incomplete'], ['Evidence references', evidenceRefs], ['Images/readings', item.evidenceComplete ? 'Available' : 'Not available'], ['Evidence verified state', item.evidenceComplete ? 'Verified by Inspector' : 'Pending verification']])}</Section>
      <Section title="F · Calculation summary">{grid([['Readings', field(item.readingsSummary, item.evidenceComplete ? 'Recorded in guided test' : 'Pending readings')], ['Error / corrected error', field(item.calculationSummary, item.evidenceComplete ? 'Within tolerance' : 'Pending calculation')], ['MPE status', item.evidenceComplete ? 'Pass' : 'Pending'], ['Calculation result', item.evidenceComplete ? 'Conforming' : 'Pending'], ['Calculation completed state', item.evidenceComplete ? 'Complete' : 'Pending']])}</Section>
      <Section title="G · TrustGate summary">{grid([['Readiness score', `${item.trustgateReady}%`], ['Result', item.trustgateResult], ['Validation status', item.trustgateReady >= 90 ? 'Passed' : 'Pending'], ['Evidence completeness', item.evidenceComplete ? 'Complete' : 'Incomplete'], ['Decision readiness', item.status === 'APPROVED' || generated ? 'Ready' : 'Pending']])}</Section>
      <Section title="H · Lab verification">{grid([['Lab review status', labStatus], ['Lab verifier', labVerifierName], ['Lab verifier remarks', data.events.find(event => event.actorRole === 'Lab Verifier' && event.remarks)?.remarks || 'Technical evidence is sufficient.'], ['Forwarded-to-officer event', data.events.some(event => event.action.toLowerCase().includes('forwarded')) ? 'Recorded' : 'Pending'], ['Technical sufficiency result', item.status === 'OFFICER_REVIEW_PENDING' || approved || generated ? 'Sufficient' : 'Pending']])}</Section>
      <Section title="I · Officer decision">{grid([['Officer', officerName], ['Officer review status', approved || generated ? 'Completed' : 'Pending'], ['Approval decision', approved || generated ? 'Approved' : 'Pending'], ['Approval remarks', data.events.find(event => event.actorRole === 'Officer' && event.remarks)?.remarks || item.remarks], ['Approval timestamp', formatTimestamp(eventTimestamp(data.events.find(event => event.actorRole === 'Officer' && event.toStatus === 'APPROVED')))]])}</Section>
      <Section title="J · Audit summary"><div className="report-event-list">{data.events.length ? data.events.map(event => <div className="report-event" key={event.id}><div><strong>{event.action}</strong><span>{event.caseId} · {event.actorRole} · {event.actorName}</span><p>{event.fromStatus || 'Created'} → {event.toStatus || 'Recorded'} · {formatTimestamp(eventTimestamp(event))}</p>{event.remarks && <p>{event.remarks}</p>}</div></div>) : <p className="section-note">No audit events recorded for this case.</p>}</div></Section>
    </article>
  </section>
}

export default DynamicReportPreview
