'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, ArrowRight, CheckCircle2, ClipboardCheck, FileCheck2, FilePlus2, RefreshCw, Search, ShieldCheck } from 'lucide-react'
import type { WorkflowCase, WorkflowRole } from '@/lib/workflow-engine'

type Section = 'overview' | 'create' | 'cases' | 'workflow' | 'report' | 'audit'
type Event = { id: string; action: string; actorName?: string; actorRole?: string; fromStatus?: string; toStatus?: string; remarks?: string; timestamp?: string; createdAt?: string }
type Props = { initialSection?: Section; initialCaseId?: string }

const sections: Array<[Section, string]> = [['overview', 'Overview'], ['create', 'Create Inspection Case'], ['cases', 'My Inspection Cases'], ['workflow', 'Active Case Workflow'], ['report', 'Draft Report Preview'], ['audit', 'Audit Summary']]
const labels = (value?: string) => value ? value.replaceAll('_', ' ').replace(/(^| )\w/g, letter => letter.toUpperCase()) : 'Not recorded'
const dateLabel = (value?: string) => { if (!value) return 'Not recorded'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Not recorded' : date.toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) }
const nextAction = (item?: WorkflowCase | null) => { if (!item) return 'Create an inspection case'; const actions: Record<string, string> = { DRAFT: 'Complete Instrument Identity', IDENTITY_COMPLETED: 'Complete Test Setup', TEST_SETUP_COMPLETED: 'Capture Evidence', EVIDENCE_CAPTURE_IN_PROGRESS: 'Complete Evidence', EVIDENCE_COMPLETED: 'Run TrustGate', TRUSTGATE_PASSED: 'Submit to Lab Verifier', SENT_BACK_TO_INSPECTOR: 'Review remarks and update evidence', RETEST_REQUESTED: 'Complete retest evidence' }; return actions[item.status] || (item.ownerRole === 'Inspector' ? 'Review case details' : `Waiting for ${item.ownerRole}`) }
const actionFor = (item: WorkflowCase) => { const actions: Record<string, [string, string]> = { DRAFT: ['Complete Instrument Identity', 'complete-passport'], IDENTITY_COMPLETED: ['Complete Test Setup', 'complete-test-setup'], TEST_SETUP_COMPLETED: ['Capture Evidence', 'open-evidence'], EVIDENCE_CAPTURE_IN_PROGRESS: ['Complete Evidence', 'capture-evidence'], EVIDENCE_COMPLETED: ['Run TrustGate', 'run-trustgate'], TRUSTGATE_PASSED: ['Submit to Lab Verifier', 'submit-to-lab'], SENT_BACK_TO_INSPECTOR: ['Review and Resubmit Evidence', 'open-evidence'], RETEST_REQUESTED: ['Complete Retest Evidence', 'open-evidence'] }; return actions[item.status] }

export function InspectorWorkspace({ initialSection = 'overview', initialCaseId }: Props) {
  const [section, setSection] = useState<Section>(initialSection)
  const [cases, setCases] = useState<WorkflowCase[]>([])
  const [activeId, setActiveId] = useState(initialCaseId || '')
  const [events, setEvents] = useState<Event[]>([])
  const [form, setForm] = useState({ inspector: '', district: '', location: '', instrument: '', inspectionDate: '', purpose: '', officer: '', priority: 'Normal', mode: 'Field', remarks: '' })
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const createRef = useRef<HTMLElement>(null)
  const workflowRef = useRef<HTMLElement>(null)
  const reportRef = useRef<HTMLElement>(null)
  const activeCase = cases.find(item => item.id === activeId) || null
  const inspectorCases = useMemo(() => cases.filter(item => item.ownerRole === 'Inspector' || item.inspector === form.inspector || ['REPORT_GENERATED', 'CLOSED'].includes(item.status)), [cases, form.inspector])
  const stats = { total: inspectorCases.length, draft: inspectorCases.filter(item => item.status === 'DRAFT').length, pending: inspectorCases.filter(item => ['NEEDS_EVIDENCE', 'SENT_BACK_TO_INSPECTOR', 'RETEST_REQUESTED'].includes(item.status)).length, ready: inspectorCases.filter(item => item.status === 'TRUSTGATE_PASSED').length, reports: inspectorCases.filter(item => item.reportGenerated || item.status === 'REPORT_GENERATED').length }

  const load = async (caseId = activeId) => { setError(''); const response = await fetch('/api/workflow/cases', { cache: 'no-store' }); if (!response.ok) throw new Error('Unable to load live inspection cases.'); const payload = await response.json(); setCases(Array.isArray(payload) ? payload : []); if (caseId) { const eventResponse = await fetch(`/api/workflow/events?caseId=${encodeURIComponent(caseId)}`, { cache: 'no-store' }); const remoteEvents = eventResponse.ok ? await eventResponse.json() : []; setEvents(Array.isArray(remoteEvents) ? remoteEvents : []) } }
  useEffect(() => { const params = new URLSearchParams(window.location.search); const step = params.get('step'); const caseId = initialCaseId || params.get('caseId') || ''; const mapped: Record<string, Section> = { 'Create Case': 'create', 'Inspection Cases': 'cases', 'Case Workflow': 'workflow', Reports: 'report', 'Audit Trail': 'audit' }; if (mapped[step || '']) setSection(mapped[step || '']); if (caseId) setActiveId(caseId); load(caseId).catch(caught => setError(caught instanceof Error ? caught.message : 'Unable to load workflow data.')) }, [initialCaseId])
  useEffect(() => { const focus = section === 'create' ? createRef : section === 'workflow' ? workflowRef : section === 'report' ? reportRef : null; focus?.current?.scrollIntoView({ block: 'start' }) }, [section])
  useEffect(() => { if (activeId) load(activeId).catch(caught => setError(caught instanceof Error ? caught.message : 'Unable to refresh workflow data.')) }, [activeId])

  const focus = (next: Section, caseId = activeId) => { setActiveId(caseId); setSection(next); if (next === 'workflow' || next === 'report') load(caseId).catch(() => undefined) }
  const runAction = async (action: string) => { if (!activeCase) return; setError(''); setMessage(''); const response = await fetch(`/api/workflow/cases/${encodeURIComponent(activeCase.id)}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ actor: { role: 'Inspector', name: form.inspector || activeCase.inspector || 'Inspector' }, remarks: activeCase.remarks || '' }) }); if (!response.ok) { setError((await response.json().catch(() => ({}))).error || 'Workflow action failed.'); return } setMessage('Workflow action saved to Neon.'); await load(activeCase.id) }
  const saveCase = async (continueToWorkflow = false) => { setError(''); setMessage(''); const id = form.inspector && form.instrument ? undefined : undefined; const response = await fetch('/api/workflow/cases', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, inspector: form.inspector, district: form.district, location: form.location, inspectionLocation: form.location, instrument: form.instrument, instrumentType: form.instrument, inspectionDate: form.inspectionDate, purpose: form.purpose, assignedOfficer: form.officer, officerName: form.officer, priority: form.priority, inspectionMode: form.mode, remarks: form.remarks, actor: { role: 'Inspector', name: form.inspector || 'Inspector' } }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setError(payload.error || 'Unable to save draft.'); return } setMessage('Case saved successfully.'); setActiveId(payload.id); await load(payload.id); if (continueToWorkflow) { setSection('workflow'); await new Promise(resolve => requestAnimationFrame(resolve)); workflowRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) } else setSection('cases') }
  const setField = (name: keyof typeof form, value: string) => setForm(current => ({ ...current, [name]: value }))

  const switchRole = (next: string) => { localStorage.setItem('trustgate-selected-role', next); window.location.href = '/dashboard' }
  return <div className="app-shell inspector-app-shell"><aside className="sidebar"><div className="brand-row"><div className="brand-mark"><ShieldCheck size={18}/></div><div><div className="brand-name">PramaanSetu</div><div className="brand-subtitle">Legal Metrology Platform</div></div></div><div className="department-chip"><div className="ashoka-mark"><ShieldCheck size={14}/></div><div><strong>Legal Metrology</strong><span>Department of Consumer Affairs</span></div></div><nav className="nav-area" aria-label="Primary navigation"><div className="nav-group"><div className="nav-label">Workspace</div>{([['overview','Dashboard'],['create','Create Case'],['cases','Inspection Cases'],['workflow','Case Workflow'],['report','Reports'],['audit','Audit Trail']] as Array<[Section,string]>).map(([key,label]) => <button key={key} className={`nav-item ${section === key ? 'nav-active' : ''}`} onClick={() => focus(key)}>{key === 'overview' ? <ClipboardCheck size={16}/> : key === 'create' ? <FilePlus2 size={16}/> : key === 'cases' ? <Activity size={16}/> : key === 'workflow' ? <ClipboardCheck size={16}/> : key === 'report' ? <FileCheck2 size={16}/> : <Activity size={16}/>}<span>{label}</span></button>)}</div></nav><div className="sidebar-bottom"><div className="sidebar-footer"><span className="online-dot"/>System operational</div></div></aside><main className="main-content"><header className="topbar"><div className="breadcrumbs"><span>PramaanSetu</span><strong>›</strong><strong>Inspector Workspace</strong></div><div className="topbar-actions"><button className="icon-button" aria-label="Search unavailable" title="Global search is not configured" disabled><Search size={17}/></button><span className="role-select"><span className="avatar">IN</span><select aria-label="Select role" value="Inspector" onChange={event => switchRole(event.target.value)}><option>Inspector</option><option>Lab Verifier</option><option>Officer</option><option>Admin</option></select></span></div></header><div className="page-wrap"><main className="inspector-workspace" aria-label="Inspector Workspace">
    <div className="workspace-heading"><div><p className="eyebrow">INSPECTOR ROLE · CENTRALIZED WORKSPACE</p><h1>{section === 'overview' ? 'Inspector Dashboard' : sections.find(([key]) => key === section)?.[1] || 'Inspector Workspace'}</h1><p className="section-note">{section === 'overview' ? 'Live inspection work at a glance.' : 'Focused view for the selected workspace task.'}</p></div><div className="workspace-heading-actions"><span className="role-pill">Inspector</span><button className="primary-button" onClick={() => focus('create')}><FilePlus2 size={15}/>Create New Case</button></div></div>
    {error && <div className="validation" role="alert">{error}</div>}{message && <div className="success-message" role="status"><CheckCircle2 size={16}/>{message}</div>}
    
    {section === 'overview' && <section className="workspace-section" id="overview"><div className="section-heading"><div><p className="eyebrow">A · OVERVIEW</p><h2>Today&apos;s inspection picture</h2></div><button className="icon-button" aria-label="Refresh live cases" onClick={() => load().catch(() => undefined)}><RefreshCw size={16}/></button></div><div className="summary-grid"><Stat label="My inspection cases" value={stats.total}/><Stat label="Draft cases" value={stats.draft}/><Stat label="Evidence pending" value={stats.pending}/><Stat label="Ready for TrustGate" value={stats.ready}/><Stat label="Reports generated" value={stats.reports}/></div><div className="overview-callout"><div><span>Current active case</span><strong>{activeCase?.id || 'No case selected'}</strong></div><div><span>Next required action</span><strong>{nextAction(activeCase)}</strong></div><div><span>Selected role</span><strong>Inspector</strong></div></div></section>}
    {section === 'create' && <section ref={createRef} className="workspace-section" id="create"><div className="section-heading"><div><p className="eyebrow">B · CREATE INSPECTION CASE</p><h2>Start a new inspection</h2></div></div><div className="form-grid">{([['inspector','Inspector name'],['district','District'],['location','Inspection location'],['instrument','Instrument type'],['inspectionDate','Inspection date'],['purpose','Purpose of inspection'],['officer','Assigned officer'],['priority','Priority'],['mode','Inspection mode']] as Array<[keyof typeof form,string]>).map(([name,label]) => <label className="form-field" key={name}><span>{label}</span><input type={name === 'inspectionDate' ? 'date' : 'text'} value={form[name]} onChange={event => setField(name, event.target.value)} placeholder={label}/></label>)}<label className="form-field form-field-wide"><span>Remarks</span><textarea rows={3} value={form.remarks} onChange={event => setField('remarks', event.target.value)} placeholder="Add inspection context or handoff notes"/></label></div><div className="workspace-actions"><button className="secondary-button" onClick={() => saveCase(false)}>Save Draft</button><button className="primary-button" onClick={() => saveCase(true)}>Save &amp; Continue to Workflow <ArrowRight size={15}/></button></div></section>}
    {section === 'cases' && <section className="workspace-section" id="cases"><div className="section-heading"><div><p className="eyebrow">C · MY INSPECTION CASES</p><h2>Live cases from Neon</h2></div><div className="case-search"><Search size={15}/><span>Inspector-owned and returned cases</span></div></div><div className="table-wrap"><table><thead><tr><th>Case ID</th><th>Instrument</th><th>Location</th><th>Status</th><th>Owner</th><th>Next action</th><th>Last updated</th><th>Action</th></tr></thead><tbody>{inspectorCases.map(item => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.instrument}</td><td>{item.location}</td><td><span className="status-badge status-blue"><span className="status-dot"/>{labels(item.status)}</span></td><td>{item.ownerRole}</td><td>{nextAction(item)}</td><td>{dateLabel(item.updatedAt)}</td><td><button className="text-button" onClick={() => focus('workflow', item.id)}>Open in Workspace</button>{(item.reportGenerated || item.status === 'REPORT_GENERATED') && <button className="text-button" onClick={() => focus('report', item.id)}>View Report</button>}<button className="text-button" onClick={() => focus('audit', item.id)}>View Audit</button></td></tr>)}{!inspectorCases.length && <tr><td colSpan={8} className="empty-state">No Inspector cases are available from Neon.</td></tr>}</tbody></table></div></section>}
    {section === 'workflow' && <section ref={workflowRef} className="workspace-section" id="workflow"><div className="section-heading"><div><p className="eyebrow">D · ACTIVE CASE WORKFLOW</p><h2>{activeCase?.id || 'Select a case to continue'}</h2></div>{activeCase && <span className="status-badge status-blue"><span className="status-dot"/>{labels(activeCase.status)}</span>}</div>{activeCase ? <><div className="case-meta-grid"><Meta label="Instrument" value={activeCase.instrument}/><Meta label="Location" value={activeCase.location}/><Meta label="Owner role" value={activeCase.ownerRole}/><Meta label="Last updated" value={dateLabel(activeCase.updatedAt)}/><Meta label="TrustGate readiness" value={`${activeCase.trustgateReady ?? 0}%`}/></div><div className="workflow-tracker">{['Instrument Identity','Test Setup','Evidence Capture','Calculation','TrustGate Review','Lab Review','Officer Approval','Report Generated','Admin Audit'].map((step, index) => <div className={`workflow-step ${index <= (activeCase.status === 'REPORT_GENERATED' ? 7 : activeCase.status.includes('EVIDENCE') ? 2 : activeCase.status === 'TRUSTGATE_PASSED' ? 4 : activeCase.status === 'SUBMITTED_TO_LAB' ? 5 : 0) ? 'complete' : ''}`} key={step}><span>{index + 1}</span>{step}</div>)}</div><div className="action-card"><div><p className="eyebrow">INSPECTOR ACTION</p><h3>{actionFor(activeCase)?.[0] || nextAction(activeCase)}</h3><p>{actionFor(activeCase) ? 'This action is available for the active workflow state and will be saved to Neon.' : 'This case is waiting for another role or is ready for read-only review.'}</p></div>{actionFor(activeCase) && <button className="primary-button" onClick={() => runAction(actionFor(activeCase)![1])}>{actionFor(activeCase)![0]} <ArrowRight size={15}/></button>}</div><div className="workflow-footer-actions"><button className="secondary-button" onClick={() => focus('report', activeCase.id)}><FileCheck2 size={15}/>View Draft Preview</button><button className="secondary-button" onClick={() => focus('audit', activeCase.id)}><Activity size={15}/>View Full Audit Trail</button></div></> : <div className="empty-state">Select a case from My Inspection Cases to see the active workflow.</div>}</section>}
    {section === 'report' && <section ref={reportRef} className="workspace-section" id="report"><div className="section-heading"><div><p className="eyebrow">E · DRAFT REPORT PREVIEW</p><h2>{activeCase?.id || 'Select a case'}</h2></div></div>{activeCase ? <div className="draft-report-card"><div className="report-preview-header"><div><p className="eyebrow">LEGAL METROLOGY · DEPARTMENT OF CONSUMER AFFAIRS</p><h3>{activeCase.reportGenerated ? 'NAWI Inspection Report' : 'Draft Report Preview'}</h3><p>Draft — not legally final</p></div><span className="status-badge status-orange"><span className="status-dot"/>{activeCase.reportGenerated ? 'Final generated' : 'Not legally final'}</span></div><div className="report-preview-grid"><Meta label="Case ID" value={activeCase.id}/><Meta label="Current status" value={labels(activeCase.status)}/><Meta label="Owner role" value={activeCase.ownerRole}/><Meta label="Last updated" value={dateLabel(activeCase.updatedAt)}/></div><p className="section-note">{activeCase.reportGenerated ? 'Final report is available read-only for Inspector review.' : 'PDF export will be available after final report generation.'}</p><div className="workspace-actions"><button className="secondary-button" disabled>PDF Export (available after final report generation)</button><button className="secondary-button" onClick={() => window.location.href = `/audit?caseId=${encodeURIComponent(activeCase.id)}`}>View Full Audit Trail</button></div></div> : <div className="empty-state">Select a case to view its draft report preview.</div>}</section>}
    {section === 'audit' && <section className="workspace-section" id="audit"><div className="section-heading"><div><p className="eyebrow">F · AUDIT SUMMARY</p><h2>Latest workflow events</h2></div></div>{activeCase ? <><div className="audit-list">{events.slice().sort((a,b) => String(b.timestamp || b.createdAt).localeCompare(String(a.timestamp || a.createdAt))).slice(0, 6).map(event => <div className="audit-row" key={event.id}><div><strong>{event.action}</strong><span>{event.actorName || 'Not recorded'} · {event.actorRole || 'Not recorded'}</span></div><div><span>{event.fromStatus ? `${labels(event.fromStatus)} → ` : ''}{labels(event.toStatus)}</span><small>{dateLabel(event.timestamp || event.createdAt)}</small></div></div>)}{!events.length && <div className="empty-state">No audit events recorded for this case.</div>}</div><button className="secondary-button" onClick={() => window.location.href = `/audit?caseId=${encodeURIComponent(activeCase.id)}`}>View Full Audit Trail</button></> : <div className="empty-state">Select a case to see its audit summary.</div>}</section>}
  </main></div></main></div>
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="summary-card"><span>{label}</span><strong>{value}</strong></div> }
function Meta({ label, value }: { label: string; value: string }) { return <div className="meta-item"><span>{label}</span><strong>{value || 'Not recorded'}</strong></div> }
