'use client'

import { useMemo } from 'react'
import type { WorkflowCase } from '@/lib/workflow-engine'

type Props = { role: 'Lab Verifier' | 'Officer' | 'Admin'; cases: WorkflowCase[]; onOpen: (id: string) => void; onAction?: (id: string, action: string) => void }

const labStatuses = new Set(['SUBMITTED_TO_LAB', 'LAB_REVIEW_IN_PROGRESS'])
const officerStatuses = new Set(['OFFICER_REVIEW_PENDING', 'OFFICER_REVIEW_IN_PROGRESS', 'APPROVED', 'REPORT_GENERATED', 'POTENTIAL_NON_COMPLIANCE'])
const label = (value: string) => value.replaceAll('_', ' ')

export function LiveRoleWorkspace({ role, cases, onOpen, onAction }: Props) {
  const visible = useMemo(() => role === 'Admin' ? cases : cases.filter(item => item.ownerRole === role || (role === 'Lab Verifier' ? labStatuses.has(item.status) : officerStatuses.has(item.status))), [cases, role])
  const reports = cases.filter(item => item.reportGenerated || item.status === 'REPORT_GENERATED')
  const metrics = role === 'Admin' ? [
    ['Total cases', cases.length], ['Open cases', cases.filter(item => item.status !== 'REPORT_GENERATED').length], ['Reports generated', reports.length], ['Sent back', cases.filter(item => item.status.includes('SENT_BACK')).length], ['Non-compliance', cases.filter(item => item.status === 'POTENTIAL_NON_COMPLIANCE').length],
  ] : []
  return <section className="workflow-card wide-card">
    <div className="card-heading"><div><p className="eyebrow">{role.toUpperCase()} WORKSPACE</p><h2>{role === 'Admin' ? 'Live administration' : role === 'Officer' ? 'Officer decision queue' : 'Technical verification queue'}</h2><p>Live workflow data from Neon PostgreSQL. No sample cases are displayed.</p></div><span className="status-badge status-green"><span className="status-dot"/>{visible.length} active</span></div>
    {role === 'Admin' && <div className="summary-grid admin-summary">{metrics.map(([name, value]) => <article className="summary-card" key={name}><div className="summary-value">{value}</div><div className="summary-label">{name}</div></article>)}</div>}
    {visible.length === 0 ? <div className="empty-state">No active cases for this role.</div> : <div className="table-wrap"><table><thead><tr><th>Case</th><th>Instrument</th><th>Location</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><button className="case-link" onClick={() => onOpen(item.id)}>{item.id}</button></td><td>{item.instrument}</td><td>{item.location}</td><td>{label(item.status)}</td><td>{new Date(item.updatedAt).toLocaleString('en-IN')}</td><td><button className="secondary-button" onClick={() => onOpen(item.id)}>View case</button>{role === 'Lab Verifier' && item.status === 'SUBMITTED_TO_LAB' && <button className="text-button" onClick={() => onAction?.(item.id, 'start-lab-review')}>Start Lab Review</button>}{role === 'Lab Verifier' && item.status === 'LAB_REVIEW_IN_PROGRESS' && <><button className="text-button" onClick={() => onAction?.(item.id, 'forward-to-officer')}>Forward to Officer</button><button className="text-button" onClick={() => onAction?.(item.id, 'send-back-to-inspector')}>Send Back</button><button className="text-button" onClick={() => onAction?.(item.id, 'recommend-retest')}>Recommend Retest</button></>}{role === 'Officer' && item.status === 'OFFICER_REVIEW_PENDING' && <button className="text-button" onClick={() => onAction?.(item.id, 'start-officer-review')}>Start Officer Review</button>}{role === 'Officer' && item.status === 'OFFICER_REVIEW_IN_PROGRESS' && <><button className="text-button" onClick={() => onAction?.(item.id, 'approve')}>Approve Report</button><button className="text-button" onClick={() => onAction?.(item.id, 'send-back-to-inspector')}>Send Back to Inspector</button><button className="text-button" onClick={() => onAction?.(item.id, 'request-retest')}>Request Retest</button><button className="text-button" onClick={() => onAction?.(item.id, 'mark-potential-non-compliance')}>Mark Potential Non-Compliance</button></>}{role === 'Officer' && item.status === 'APPROVED' && <button className="text-button" onClick={() => onAction?.(item.id, 'generate-report')}>Generate Report</button>}{role === 'Officer' && item.status === 'REPORT_GENERATED' && <button className="text-button" onClick={() => onOpen(item.id)}>View Report</button>}{role === 'Admin' && <><button className="text-button" onClick={() => window.location.href = `/audit?caseId=${encodeURIComponent(item.id)}`}>Open Audit</button>{(item.reportGenerated || item.status === 'REPORT_GENERATED') && <button className="text-button" onClick={() => window.location.href = `/reports/${encodeURIComponent(item.id)}`}>Open Report</button>}</>}</td></tr>)}</tbody></table></div>}
    {role === 'Admin' && <><h3 className="section-title">Generated reports</h3>{reports.length === 0 ? <div className="empty-state">No generated reports yet.</div> : <div className="table-wrap"><table><thead><tr><th>Case</th><th>Report ID</th><th>Instrument</th><th>Location</th><th>Decision</th><th>Action</th></tr></thead><tbody>{reports.map(item => <tr key={item.id}><td>{item.id}</td><td>{item.reportId || 'Not recorded'}</td><td>{item.instrument}</td><td>{item.location}</td><td>{item.remarks || label(item.status)}</td><td><button className="text-button" onClick={() => window.location.href = `/reports/${encodeURIComponent(item.id)}`}>View report</button></td></tr>)}</tbody></table></div>}</>}
  </section>
}
