'use client'

import { ArrowDownRight, ArrowRight, BadgeCheck, Check, ClipboardCheck, FileCheck2, Gauge, Landmark, LockKeyhole, Scale, ShieldCheck, Users, Workflow } from 'lucide-react'

const workflow = [
  ['Instrument Intake', 'Register inspection case and instrument details.', 'Owned by Inspector'],
  ['NAWI Passport', 'Verify manufacturer, model, serial, class, capacity and interval.', 'Verified identity'],
  ['OIML Test Selection', 'Select applicable R 76 tests from the instrument profile.', 'Rule-based'],
  ['Evidence Capture', 'Record readings, load points, photos and timestamps.', 'Evidence required'],
  ['TrustGate Review', 'Check completeness, consistency and decision readiness.', 'Decision gate'],
  ['Officer Approval', 'Approve the outcome, send back, or request a retest.', 'Officer authority'],
  ['Report & Audit Trail', 'Generate the report and preserve the full action history.', 'Audit-ready output'],
] as const
const roles = [
  { number:'01', category:'FIELD OPERATIONS', title:'Inspector', mission:'Creates the source inspection record and captures instrument identity, readings and evidence.', responsibilities:['Create inspection case','Register NAWI identity and setup','Capture readings, photos and evidence'], can:['Create and update cases','Record evidence and guided test data','Submit case for review'], cannot:['Approve final outcome','Generate officer-authorized report'], Icon:ClipboardCheck },
  { number:'02', category:'TECHNICAL VERIFICATION', title:'Lab Verifier', mission:'Checks setup, readings, evidence quality and retest need before decision finalization.', responsibilities:['Review setup and readings','Validate evidence completeness','Recommend retest or manual review'], can:['Review evidence and calculation readiness','Add technical observations','Recommend send-back / retest'], cannot:['Create source inspection case','Issue final officer decision'], Icon:Gauge },
  { number:'03', category:'DECISION AUTHORITY', title:'Officer / Authority', mission:'Makes the official decision by reviewing evidence, TrustGate status and report readiness.', responsibilities:['Review case detail and findings','Approve, send back or request retest','Authorize final report outcome'], can:['Approve or reject case progression','Mark manual review or non-compliance','Generate officer-approved report'], cannot:['Edit source evidence','Override governance rules arbitrarily'], Icon:Landmark },
  { number:'04', category:'GOVERNANCE', title:'Admin', mission:'Maintains roles, rule versions, thresholds and system governance settings.', responsibilities:['Manage users and role access','Configure rules and thresholds','Monitor system operations'], can:['Manage system configuration','Manage permissions and controls','Review cases, reports and audit records'], cannot:['Replace officer decision authority','Change evidence after completion'], Icon:LockKeyhole },
] as const

export default function TrustGateLanding() {
  return <main className="landing-page premium-landing">
    <nav className="landing-nav" aria-label="Landing page navigation"><a className="landing-brand" href="#overview"><span className="landing-mark"><ShieldCheck size={19}/></span><span><strong>PramaanSetu</strong><small>Legal Metrology Inspection System</small></span></a><div className="landing-links"><a href="#overview">Overview</a><a href="#workflow">Workflow</a><a href="#roles">Roles</a><a className="nav-cta" href="/dashboard">Enter System <ArrowRight size={14}/></a></div></nav>

    <section id="overview" className="landing-hero command-hero"><div className="hero-copy"><div className="landing-badges"><span>Legal Metrology Department</span><span>NAWI Inspection and Reporting</span></div><p className="landing-kicker">PRAAMAANSETU · OFFICIAL WORKSPACE</p><h1>NAWI Inspection and Reporting Portal</h1><p className="hero-subtitle">Evidence-linked workflow for verified instrument identity, guided testing, officer review and audit-ready reporting.</p><div className="hero-actions"><a className="landing-primary" href="/dashboard">Enter System <ArrowRight size={17}/></a><a className="landing-secondary" href="#workflow">View Workflow <ArrowDownRight size={16}/></a></div><div className="hero-proof"><span className="proof-route"><b>01</b> Inspector <i/> <b>02</b> Lab Verifier <i/> <b>03</b> Officer <i/> <b>04</b> Audit</span><span>Every handoff is linked to evidence, actor and timestamp.</span></div></div>
      <div className="command-preview" aria-label="Inspection command preview"><div className="preview-grid"/><div className="preview-top"><span className="eyebrow">INSPECTION CASE DASHBOARD</span><span className="preview-live"><i/> READY FOR OFFICER REVIEW</span></div><div className="preview-case"><div><span className="case-label">ACTIVE CASE</span><strong>TG-2026-0041</strong><span>Retail weighing scale · Bhubaneswar</span></div><span className="preview-seal"><ShieldCheck size={18}/></span></div><div className="readiness-row"><div><span className="case-label">TRUSTGATE READINESS</span><strong>96<span>%</span></strong></div><div className="readiness-ring"><b>96</b><small>READY</small></div></div><div className="preview-meter"><span style={{width:'96%'}}/></div><div className="verification-chips"><span><Check/> Identity verified</span><span><Check/> Evidence complete</span><span><Check/> Calculation checked</span><span className="amber"><i/> Officer pending</span></div><div className="chain-title"><span>TRACEABILITY CHAIN</span><b>6 linked events</b></div><div className="audit-chain">{['Passport','Evidence','Calculation','TrustGate','Officer','Report'].map((item,index)=><div key={item}><span className={index<4?'chain-done':''}>{index<4?<Check size={11}/>:index===4?'05':'06'}</span><strong>{item}</strong>{index<5&&<i/>}</div>)}</div><div className="preview-bottom"><span><BadgeCheck size={14}/> R 76-2 style report</span><span><FileCheck2 size={14}/> Audit linked</span></div></div></section>

    <section className="proof-strip" aria-label="TrustGate proof points"><div><Users size={17}/><strong>04</strong><span>Operational roles</span></div><div><Workflow size={17}/><strong>15+</strong><span>Workflow screens</span></div><div><BadgeCheck size={17}/><strong>100%</strong><span>Evidence-linked findings</span></div><div><FileCheck2 size={17}/><strong>R 76-2</strong><span>Style report</span></div><div><ShieldCheck size={17}/><strong>Complete</strong><span>Audit chain</span></div></section>

    <section className="landing-section challenge-grid"><div className="section-lead"><p className="landing-kicker">THE CONTROL PROBLEM</p><h2>When the evidence chain is weak, the decision is weak.</h2><p>Every conclusion stays linked to its source evidence.</p></div><div className="control-list">{[['01','Identity gaps','Instrument identity is often incomplete or disconnected from the final finding.'],['02','Evidence gaps','Photos, readings and observations are difficult to validate after the visit.'],['03','Decision gaps','A report can move forward before technical review and officer authority are complete.']].map(([number,title,description])=><div key={number}><b>{number}</b><span><strong>{title}</strong><small>{description}</small></span><ArrowRight size={17}/></div>)}</div></section>

    <section className="landing-section workflow-section" id="workflow"><div className="section-heading"><div><h2>One controlled workflow from instrument intake to final outcome</h2></div><p>Each stage records verified data, applies the required checks, and passes a traceable case record forward.</p></div><div className="workflow-grid">{workflow.map(([title,description,cue],index)=><article className="workflow-card" key={title}><div className="workflow-card-head"><span className="workflow-number">{String(index+1).padStart(2,'0')}</span><Workflow size={17}/></div><h3>{title}</h3><p>{description}</p><span className="workflow-cue">{cue}</span>{index<workflow.length-1&&<i className="workflow-connector" aria-hidden="true"/>}</article>)}</div><div className="workflow-note"><Workflow size={18}/><span><strong>Evidence Before Result</strong><small>No report becomes final until the case record is complete, reviewed and officer-approved.</small></span></div></section>

    <section className="landing-section roles-section" id="roles"><div className="section-heading"><div><h2>Clear ownership at every stage of the inspection process</h2></div><p>Each role performs a defined function to preserve evidence integrity, review quality, officer authority and governance control.</p></div><div className="role-grid premium-role-grid">{roles.map(({number,category,title,mission,responsibilities,can,cannot,Icon})=><article className="role-card" key={title}><div className="role-card-top"><span className="role-number">{number}</span><Icon size={19}/><p className="role-subtitle">{category}</p></div><h3>{title}</h3><p className="role-mission">{mission}</p><div className="role-responsibilities"><strong>Responsibilities</strong><ul>{responsibilities.map(item=><li key={item}>{item}</li>)}</ul></div><div className="role-permission can"><strong>Can do</strong><ul>{can.map(item=><li key={item}>{item}</li>)}</ul></div><div className="role-permission cannot"><strong>Cannot do</strong><ul>{cannot.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</div></section>

    <section className="landing-section impact-section" id="impact"><div className="impact-heading"><p className="landing-kicker">WHY IT MATTERS FOR ENFORCEMENT</p><h2>Stronger records. Clearer decisions.</h2><p>PramaanSetu reduces weak records, false findings and untraceable decisions across the inspection lifecycle.</p></div><div className="impact-list"><article><ShieldCheck size={19}/><b>Stronger Inspection Records</b><small>Every result is linked to identity, readings, evidence and officer action.</small></article><article><Scale size={19}/><b>Fewer False Findings</b><small>Counter-evidence and retest paths prevent premature non-compliance marking.</small></article><article><Workflow size={19}/><b>Faster Review</b><small>Role-specific dashboards reduce follow-up and missing information.</small></article><article><FileCheck2 size={19}/><b>Audit-Ready Decisions</b><small>Each step records role, timestamp, status and report context.</small></article></div></section>

    <section className="landing-cta"><div><p className="landing-kicker">ROLE-BASED SYSTEM ACCESS</p><h2>Proceed to the inspection workspace</h2><p>Access is assigned by operational role and recorded in the case audit trail.</p><div className="cta-roles"><span>Inspector</span><span>Lab Verifier</span><span>Officer</span><span>Admin</span></div></div><a className="landing-primary" href="/dashboard">Enter System <ArrowRight size={17}/></a></section><footer className="landing-footer"><span>TrustGate NAWI Reporting Portal</span><span>Legal Metrology Inspection System · Audit-ready workflow</span></footer>
  </main>
}

export { roles }
export type { }

